### ISSUE TITLE
Add tests for action in a GitHub Wokflow

### ISSUE THREAD

**Issue by emibcn** [johanvanhelden/clover-coverage-check#6]
Ideally I would like to have some sort of automatic testing set up. Since it's quite time consuming to test this action manually :thinking:

_Originally posted by @johanvanhelden in https://github.com/johanvanhelden/gha-clover-test-coverage-check/pull/4#issuecomment-689826575_

**Comment by johanvanhelden** [comment]
I am starting to work this issue first.

https://github.com/johanvanhelden/gha-clover-test-coverage-check/pull/7
